#!/bin/sh
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 2
# @author    Gerik Bonaert <dev@adaxisoft.be>
# @copyright Copyright (c) 2013 Gerik Bonaert
#
# Sabnzbdplus for OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_SABNZBDPLUS_RUN_AS=${OMV_SABNZBDPLUS_RUN_AS:-"essencia"}
OMV_SABNZBDPLUS_PORT=${OMV_SABNZBDPLUS_PORT:-"8080"}
OMV_SABNZBDPLUS_INSTALL_DIR=${OMV_SABNZBDPLUS_INSTALL_DIR:-"/usr/share/sabnzbdplus"}
OMV_SABNZBDPLUS_CONFIG_DIR=${OMV_SABNZBDPLUS_CONFIG_DIR:-"/etc/sabnzbdplus"}
OMV_SABNZBDPLUS_CONFIG_FILE=${OMV_SABNZBDPLUS_CONFIG_FILE:-"${OMV_SABNZBDPLUS_CONFIG_DIR}/config.ini"}
OMV_SABNZBDPLUS_DATA_DIR=${OMV_SABNZBDPLUS_DATA_DIR:-"/var/lib/sabnzbdplus"}
OMV_SABNZBDPLUS_LOG_DIR=${OMV_SABNZBDPLUS_LOG_DIR:-"/var/log/sabnzbdplus"}
OMV_SABNZBDPLUS_DEFAULT_FILE=${OMV_SABNZBDPLUS_DEFAULT_FILE:-"/etc/default/sabnzbdplus"}
OMV_SABNZBDPLUS_WEB_ROOT=${OMV_SABNZBDPLUS_WEB_ROOT:-"/sabnzbdplus"}
OMV_SABNZBDPLUS_AUTOPROCESS_FILE=${OMV_SABNZBDPLUS_AUTOPROCESS_FILE:-"/usr/share/sabnzbdplus/autoProcessTV/autoProcessTV.cfg"}
OMV_SABNZBDPLUS_NGINX_SITE=${OMV_SABNZBDPLUS_NGINX_SITE:-"/etc/nginx/sites-available/sabnzbdplus-proxy"}

for DIR in ${OMV_SABNZBDPLUS_CONFIG_DIR} ${OMV_SABNZBDPLUS_LOG_DIR} ${OMV_SABNZBDPLUS_DATA_DIR}; do
    mkdir -p ${DIR}
    chown ${OMV_SABNZBDPLUS_RUN_AS} ${DIR} -R
done


cat <<EOF > ${OMV_SABNZBDPLUS_DEFAULT_FILE}
# This file is sourced by /etc/init.d/sabnzbdplus
#
# When sabnzbdplus is started using the init script
# is started under the account of $USER, as set below.
#
# Each setting is marked either "required" or "optional";
# leaving any required setting unconfigured will cause
# the service to not start.


# [optional] change to 1 to enable daemon
ENABLE_DAEMON=1

# [required] user or uid of account to run the program as:
USER=${OMV_SABNZBDPLUS_RUN_AS}

# [optional] change to 1 to enable updating from webinterface
# this changes ownership of /opt/sabnzbdplus to user set @ RUN_AS=
WEB_UPDATE=1

# [optional] full path to the configuration file of your choice;
# otherwise, the default location (~/.sabnzbdplus) is used:
CONFIG=${OMV_SABNZBDPLUS_CONFIG_FILE}

# [required] host to listen on:
HOST=0.0.0.0

# [optional] port number to listen on:
PORT=${OMV_SABNZBDPLUS_PORT}

EOF

cat <<EOF > ${OMV_SABNZBDPLUS_NGINX_SITE}
location /usenet/ {
    proxy_pass http://localhost:8080/;
}
EOF

nginx_ensite sabnzbdplus-proxy
service nginx reload



 
